Update extraction to zip instead of tar. Move work to postbuild instead of postinstall.

diff --git a/postbuild b/postbuild
--- a/postbuild
+++ b/postbuild
@@ -1,18 +1,32 @@
-#!/bin/sh
+#!/bin/bash
+# Make this script exit at the first non-zero exit code. Fast-fail.
+set -e
 
 name="phpMyAdmin"
 url="http://sourceforge.net/projects/phpmyadmin/files/latest/download?source=files"
+# Version 4.0.0 seems to be a zip file rather than tar.bz2
+outfile="phpmyadmin.latest.zip"
 
-install_dir=~/data/pma/
+install_dir=~/data/installedPhpMyAdmin
 
 msg() {
-    echo "$name: $*." >&2
+    echo "$name: $*."
 }
 
-die() {
-    [ $# -ne 0 ] && msg $*
-
-    exit 1
+# Emulate tar's --strip-components=1
+unzipstrip() {
+    local zip=$1
+    local dest=${2:-.}
+    local temp=$(mktemp -d)
+    unzip -d "$temp" "$zip"
+    mkdir -p "$dest"
+    shopt -s dotglob
+    local f=("$temp"/*)
+    if (( ${#f[@]} == 1 )) && [[ -d "${f[0]}" ]] ; then
+        mv "$temp"/*/* "$dest"
+    else
+        mv "$temp"/* "$dest"
+    fi && rmdir "$temp"/* "$temp"
 }
 
 install_pma() {
@@ -20,9 +34,13 @@ install_pma() {
         msg "downloading and installing the latest version"
 
         [ -d $install_dir ] || mkdir -p $install_dir
-        curl -sSL --retry 3 $url | tar --strip-components=1 -jxf - -C $install_dir
+        curl -sSL --retry 3 -o $outfile $url 
+	
+	msg "Download successful. Unpacking."
+	unzipstrip $outfile $install_dir
+	# Swap this for unzip if phpMyAdmin goes back to tar.bz2
+	# tar --strip-components=1 -xf $outfile -C $install_dir
 
-        [ $? -ne 0 ] && die "installation failed"
     else
         msg "phpMyAdmin already installed"
     fi
